// Generated by CoffeeScript 1.7.1
(function() {
  var Test, wishlist;

  wishlist = typeof npmWishlist !== "undefined" && npmWishlist !== null ? npmWishlist : require("../wishlist");

  Test = wishlist.Test;

  new Test("root").add(function(my, I) {
    return I.wish(' true=true ');
  }).run();

}).call(this);
