// Generated by CoffeeScript 1.7.1
(function() {
  var Test, wishlist;

  wishlist = (typeof exports !== "undefined" && exports !== null) && ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) ? require("../wishlist") : npmWishlist;

  Test = wishlist.Test;

  new Test("root").add(function() {
    return unit(' true=true ');
  }).run();

}).call(this);
